"""add functionality to appointments

Revision ID: 3047f86296bf
Revises: b292dd8e9f33
Create Date: 2025-03-13 10:38:30.981161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3047f86296bf'
down_revision: Union[str, None] = 'b292dd8e9f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'dentist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('appointments', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('dentists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dentists', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dentists', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_dentists_id'), 'dentists', ['id'], unique=False)
    op.create_index(op.f('ix_dentists_name'), 'dentists', ['name'], unique=False)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_dentists_name'), table_name='dentists')
    op.drop_index(op.f('ix_dentists_id'), table_name='dentists')
    op.alter_column('dentists', 'contact_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dentists', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dentists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'dentists', ['dentist_id'], ['id'])
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.alter_column('appointments', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('appointments', 'dentist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
